# Generated by Django 5.2.8 on 2025-11-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_messagecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissions', models.PositiveIntegerField(default=0)),
                ('journees_hospitalisation', models.PositiveIntegerField(default=0)),
                ('taux_occupation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('duree_moy_sejour', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taux_mortalite', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activite', to='gestion.service')),
            ],
        ),
        migrations.CreateModel(
            name='EffectifService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professeurs', models.PositiveIntegerField(default=0)),
                ('specialistes', models.PositiveIntegerField(default=0)),
                ('generalistes', models.PositiveIntegerField(default=0)),
                ('paramedicaux', models.PositiveIntegerField(default=0)),
                ('autres', models.PositiveIntegerField(default=0)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='effectifs', to='gestion.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_lits', models.PositiveIntegerField(default=0)),
                ('cout_journee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='gestion.service')),
            ],
        ),
        migrations.CreateModel(
            name='UniteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('nombre', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='gestion.service')),
            ],
        ),
    ]
