# Generated by Django 5.2.8 on 2025-11-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_activiteservice_effectifservice_servicedetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='service',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='medecins', to='gestion.service'),
            preserve_default=False,
        ),
    ]
