# Generated by Django 5.2.8 on 2025-11-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_medecin_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniteservice',
            old_name='nombre',
            new_name='lits',
        ),
    ]
