# Generated by Django 5.2.8 on 2025-11-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_rename_nombre_uniteservice_lits'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='fonction',
            field=models.CharField(blank=True, choices=[('Chef de Service', 'Chef de Service'), ("Chef d'unité", "Chef d'unité"), ('Coordinateur', 'Coordinateur')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='grade',
            field=models.CharField(choices=[('Interne', 'Interne'), ('Assistant', 'Assistant'), ('Chef de Clinique', 'Chef de Clinique'), ('Professeur', 'Professeur')], default='Interne', max_length=50),
        ),
        migrations.AddField(
            model_name='medecin',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins', to='gestion.uniteservice'),
        ),
    ]
