# Generated by Django 5.2.8 on 2025-11-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_medecin_fonction_medecin_grade_medecin_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='medecins/'),
        ),
    ]
