# Generated by Django 5.2.8 on 2025-11-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_medecin_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medecin',
            options={'ordering': ['ordre']},
        ),
        migrations.AddField(
            model_name='medecin',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
