# Generated by Django 5.2.8 on 2025-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_medecin_options_medecin_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='fonction',
            field=models.CharField(blank=True, choices=[('Chef de Service', 'Chef de Service'), ('Chef d Unité', 'Chef d Unité'), ('Coordinateur', 'Coordinateur'), ('Médecin', 'Médecin')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='grade',
            field=models.CharField(choices=[('Généraliste', 'Généraliste'), ('Généraliste Chef', 'Généraliste Chef'), ('Résident', 'Résident'), ('Praticien Spécialiste Assistant', 'Praticien Spécialiste Assistant'), ('Praticien Spécialiste Chef', 'Praticien Spécialiste Chef'), ('Praticien Spécialiste Principal', 'Praticien Spécialiste Principal'), ('Professeur', 'Professeur')], default='Interne', max_length=50),
        ),
    ]
