# Generated by Django 5.2.8 on 2025-11-27 13:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_medecin_fonction_alter_medecin_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='grade',
            field=models.CharField(choices=[('Généraliste', 'Généraliste'), ('Généraliste Chef', 'Généraliste Chef'), ('Résident', 'Résident'), ('Praticien Spécialiste Assistant', 'Praticien Spécialiste Assistant'), ('Praticien Spécialiste Chef', 'Praticien Spécialiste Chef'), ('Praticien Spécialiste Principal', 'Praticien Spécialiste Principal'), ('Professeur', 'Professeur')], default='Généraliste', max_length=50),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
